### ISSUE TITLE
theme change not working on MacOS

### ISSUE THREAD

**Issue by ciscohack** [oh-my-fish/oh-my-fish#781] opened 2020-09-30 19:16 UTC
I just installed fish shell version 3.1.2 and installed a couple of themes but theme switch not working. Secondly, I have noticed after removing all theme omf instead of using the default theme, automatically select prompt style "Classic" . I checked the directory there is no fish_prompt.fish file as well.

**Comment by ciscohack** [comment] 2020-09-30 20:34
To make it work again. I have to delete file "~/.confif/fish/config.d/config.fish" and re-add. looks to be a bug to me.

**Comment by dash2507** [comment] 2020-10-02 20:49
> To make it work again. I have to delete file "~/.confif/fish/config.d/config.fish" and re-add. looks to be a bug to me.

I also had to remove config.fish to actually see the effect. Definitely looks like a bug, but maybe it could be that way. Only using fish since a month.

**Comment by ciscohack** [comment] 2020-10-03 06:05
@dash2507  No, I don't think this is correct behaviour or any shell should work like this. it's a bug. I opened ticket thought we will get better detail and assistance but seems fish shell support is not very active. anyway removing config.fish and re-adding fixing my problem but I have to do it all time when the issue happens again.

**Comment by scorphus** [comment] 2020-12-02 20:46
Unfortunatelly, I could not reproduce this issue. I tried in my current workstation (years old installation) and also on two docker containers (arch and ubuntu — pristine environments). I could switch themes just fine.

Could you please provide further information such as parts of your `config.fish` and/or `conf.d/*` — only the non-sensitive sections — or any other information you find relevant?

**Comment by ColtonIdle** [comment] 2020-12-07 11:04
Check out my answer here potentially https://github.com/oh-my-fish/oh-my-fish/issues/671

**Comment by scorphus** [comment] 2020-12-07 18:09
Closing as a dupe of #671. Thanks, @ColtonIdle

**Closed by scorphus** 2020-12-07 18:09 UTC
