### ISSUE TITLE
Midnight commander slow on changing folders 

### ISSUE THREAD

**Issue by quenode** [oh-my-fish/oh-my-fish#414] opened 2016-10-13 15:24 UTC
Midnight commander as lot slower just changing folder when using omf . Not sure what is the problem.
But when use just normal fish work ok.

Try pressing [enter] in MC on folder you will see how much slow it works. Really annoying if you a lot MC.

**Comment by derekstavis** [comment] 2016-10-13 15:59
I'm not a MC user, but we need to investigate why the issue is happening. My only bet is that every "enter" runs a new fish shell, which can be slow depending on the number and the init time of packages you have installed.

**Comment by quenode** [comment] 2016-10-14 10:41
@derekstavis  I will post youtube to show you example what is happening.But yes I am thing about that two.

**Comment by quenode** [comment] 2016-10-14 11:53
Here is the demonstration.

![mcomfproblemtest](https://cloud.githubusercontent.com/assets/14805303/19386623/8a93683a-9215-11e6-8ad8-15fc193093e9.gif)

**Comment by oranja** [comment] 2016-12-18 08:39
Your diagnosis was right -- [|enter| handling in mc's src](https://github.com/MidnightCommander/mc/blob/0cc22928afbc6e23eb0fa5c85fd95518d8151edc/src/filemanager/command.c#L242).

Question is what to do about it.

1. You can try to open an issue in MidnightCommander's repository. I'm not sure if they can do much about it, but perhaps they will have some tips for configuring `mc` to run with bash as a subshell instead of fish.

2. I can think of some ugly workarounds:
2.1. Run `mc` under a different user in your group, with same permissions and same `$HOME` path, but a different default shell.
2.2. Follow https://github.com/fish-shell/fish-shell/issues/1301 to wrap OMF's init script (in `$OMF_PATH/init.fish`) so that it only runs in an interactive session (hoping that `mc` actually starts fish in a non-interactive mode. I think it depends if stdin/stdout are connected to some user terminal).

3. You can open a new issue here to address _2.2_, such that there can be an agreed method to start fish without loading OMF, and perhaps then it will be easier to solve the problem by just setting some environment variable before running `mc`.

**Comment by krzysztof-magosa** [comment] 2017-04-01 14:31
If you don't need subshell support in mc, just run it with `mc -u`.

**Comment by 907th** [comment] 2018-11-29 15:55
@krzysztof-magosa Thank you for the tip! I use `mc` under iTerm2 on Mac and every directory change freezes the terminal for 1-2 sec. With `mc -u` this doesn't happen!

**Comment by lnx-soul** [comment] 2021-05-01 18:29
Are we good to close this?

**Comment by quenode** [comment] 2021-07-19 08:54
> Are we good to close this?

Well depends would be better to support zsh and fish as subshell if possible or add option for users to select there  own shell if possible.   But anyways if is to much effort for this new feature than close it :D

**Comment by thompsonbrian** [comment] 2021-07-19 13:11
> Well depends would be better to support zsh and fish as subshell if possible or add option for users to select there own shell if possible

You could open a new issue with the feature request, reference this issue there, and then close this issue.  This project isn't that active, so that may be time wasted.  Your call.

**Comment by scorphus** [comment] 2021-07-23 18:49
That's, IMO, at a certain degree, a very specific need. With an easy fix. Either `mc -u` or:

> ~/.config/fish/conf.d/omf.fish
```fish
# Load Oh My Fish configuration.
if status --is-interactive
  source $OMF_PATH/init.fish
end
```

p.s.: I use functions defined by plugins in some of my scripts and I'm more than happy paying the price (as in loading time). Otherwise, they're unnecessary, and I write a bash script instead.

**Closed by scorphus** 2021-07-23 18:49 UTC
Labels: troubleshooting
