### ISSUE TITLE
Can we install fisherman's plugins with omf?

### ISSUE THREAD

**Issue by BarbzYHOOL** [oh-my-fish/oh-my-fish#614] opened 2018-05-18 22:34 UTC
Seems like the opposite is possible but I already use OMF and also wants to make good use of the other plugins

How to proceed with omf? only manual install?

**Comment by sagebind** [comment] 2018-05-18 23:17
Currently there is no easy way to do so. Most plugins designed for fisherman just dump the functions in the repository root, where OMF uses Fish's built-in autoloading using paths.

You could work around the issue by using OMF to manage the repo, and then `source` the files yourself. For example:

```sh
$ omf install https://github.com/fisherman/fishtape
```

And then in your `config.fish`:

```sh
source $OMF_PATH/pkg/fishtape/*.fish
```

**Comment by BarbzYHOOL** [comment] 2018-05-21 18:43
that seems annoying

Is it possible to use fisherman alongside oh my fish? lol

**Comment by sagebind** [comment] 2018-05-21 19:59
It would be possible to create an OMF plugin to do this automatically, but no one has done so as no one else has asked for this at this point. Basically what I'd do is create a plugin called `force-init` that has an init hook with a script like this:

```sh
for root_function in $OMF_PATH/pkg/*/*.fish
    switch $root_function
        case 'init.fish' 'key_bindings.fish'
            # Ignore hook scripts
        case '*.fish'
            # Probably a function file in the package root
            source $root_function
    end
end
```

Actually you could also put the above in your `config.fish` and all Fisherman-style plugins would work automatically (with a slight performance penalty from sourcing files on init).

**Comment by BarbzYHOOL** [comment] 2018-06-11 14:14
Sadly it's conflicting with omf plugins and also depending on the plugin it's not in the same path.

Not sure what to do

**Comment by sagebind** [comment] 2018-12-31 17:40
Closing as we have no plans on supporting this at this time. Ideally plugin authors would make sure their packages are structured such that they work with both frameworks, if possible.

**Closed by sagebind** 2018-12-31 17:40 UTC

**Comment by ngmoviedo** [comment] 2020-11-11 16:29
> It would be possible to create an OMF plugin to do this automatically, but no one has done so as no one else has asked for this at this point. Basically what I'd do is create a plugin called `force-init` that has an init hook with a script like this:
> 
> ```shell
> for root_function in $OMF_PATH/pkg/*/*.fish
>     switch $root_function
>         case 'init.fish' 'key_bindings.fish'
>             # Ignore hook scripts
>         case '*.fish'
>             # Probably a function file in the package root
>             source $root_function
>     end
> end
> ```
> 
> Actually you could also put the above in your `config.fish` and all Fisherman-style plugins would work automatically (with a slight performance penalty from sourcing files on init).

I know the issue is closed and out of the scope of the project, but I should note that this method works perfectly for me. I've tested it with bax and fish-async-prompt plugins.
I've simply created a custom plugin via `omf new` and modified init.fish as instructed.
Works also by adding those lines in config.fish, although a line about usage gets annoyingly reported at shell startup.
