### ISSUE TITLE
Conflicting prompt setting. 

### ISSUE THREAD

**Issue by toghrulgasimov** [oh-my-fish/oh-my-fish#842] opened 2021-07-08 09:03 UTC
After installing any theme. Changing theme 4 times gives error.
Installing, removing theme does not solve problem. oh-my-fish is still broken.
**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```
tg@tg ~> omf install bira
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package bira
✔ bira successfully installed.
╭─tg@tg /home/tg  ‹system› 
╰─$ omf install redfish
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package redfish
✔ redfish successfully installed.
λ { ~ }
» omf theme default
λ { ~ }
» 
λ { ~ }
» 
λ { ~ }
» omf theme default
λ { ~ }
» omf theme bira
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
Theme not installed!
Install it using omf install bira
λ { ~ }
» omf install redfish                                                       ↵ 3
Updating https://github.com/oh-my-fish/packages-main master... Done!
Error: redfish already installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
λ { ~ }
» omf doctor                                                                ↵ 1
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.1
Git core.autocrlf:    no
Warning: fish_prompt.fish is overridden.
  fish_config command persists the prompt to ~/.config/fish/functions/fish_prompt.fish
  That file takes precedence over Oh My Fish's themes. Remove the file to fix it:
  rm ~/.config/fish/functions/fish_prompt.fish

Checking for a sane environment...
If everything you use Oh My Fish for is working fine, please don't worry and just ignore the warnings. Thanks!
λ { ~ }
» omf bira
Unknown command: bira
λ { ~ }
» omf theme bira                                                            ↵ 2
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
Theme not installed!
Install it using omf install bira
λ { ~ }
» omf install bira                                                          ↵ 3
Updating https://github.com/oh-my-fish/packages-main master... Done!
Error: bira already installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
λ { ~ }
» omf doctor                                                                ↵ 1
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.1
Git core.autocrlf:    no
Warning: fish_prompt.fish is overridden.
  fish_config command persists the prompt to ~/.config/fish/functions/fish_prompt.fish
  That file takes precedence over Oh My Fish's themes. Remove the file to fix it:
  rm ~/.config/fish/functions/fish_prompt.fish

Checking for a sane environment...
If everything you use Oh My Fish for is working fine, please don't worry and just ignore the warnings. Thanks!
λ { ~ }
» omf install bira
Updating https://github.com/oh-my-fish/packages-main master... Done!
Error: bira already installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
λ { ~ }
» omf install idan                                                          ↵ 1
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package idan
✔ idan successfully installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
λ { ~ }
» omf theme idan                                                            ↵ 1
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
Theme not installed!
Install it using omf install idan
λ { ~ }
» omf install idan                                                          ↵ 3
Updating https://github.com/oh-my-fish/packages-main master... Done!
Error: idan already installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
λ { ~ }
»                         
```

**Comment by scorphus** [comment] 2021-07-23 18:50
Duplicate of #671

**Closed by scorphus** 2021-07-23 18:50 UTC
