### ISSUE TITLE
fatal: repository 'shellder' does not exist 

### ISSUE THREAD

**Issue by kylefelipe** [oh-my-fish/oh-my-fish#854] opened 2021-08-09 13:17 UTC
Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.

When installing omf it issues the follow message

```
fatal: repository 'shellder' does not exist
Could not install shellder.
Install aborted: Error installing plugins

Oh My Fish installation failed.
```

**Comment by scorphus** [comment] 2021-08-09 13:54
Hi! 👋

The shellder theme — along with a [few other packages](https://github.com/oh-my-fish/packages-main/commit/3025b1b15d1517ce0d289a3b62977e8ff518f3c4) — was removed for being archived. Please consider the theme [author's recommendation](https://github.com/simnalamburt/shellder#readme) for alternatives.

If you still use MSYS2 or for any other reason still find shellder to be relevant and wishes to maintain it, please let us know.

Closing as a duplicate of #677.

**Closed by scorphus** 2021-08-09 13:54 UTC
