### ISSUE TITLE
Omf's output is fairly messed up (lines are staggered)

### ISSUE THREAD

**Issue by AsyncMoksha** [oh-my-fish/oh-my-fish#792] opened 2020-11-28 01:51 UTC
As seen in the screenshot. Ever since installing omf, the terminal output has been messed up. The lines are staggered and hard to read.

I'm using bobthefish but this problem happened before I installed that theme.

I just installed fish, omf & bobthefish within the past hour, so all the configs are still default.

![image](https://user-images.githubusercontent.com/5743383/100491543-1eefca80-30d9-11eb-9751-5d6f542afb2f.png)

**Environment report**
```
Oh My Fish version:   7
OS type:              MacOS Mojave
Fish version:         fish, version 3.1.2
Git version:          git version 2.20.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by ColtonIdle** [comment] 2020-12-08 00:34
I have this as well when I'm changing themes. All I did was kill terminal in macos and everything worked normally again.

😄

**Comment by scorphus** [comment] 2021-01-23 20:09
Closing as a duplicate of #766

**Closed by scorphus** 2021-01-23 20:09 UTC
Labels: status: help wanted
