### ISSUE TITLE
Some themes broken post upgrade to Fish 2.5.0

### ISSUE THREAD

**Issue by JamesMcMahon** [oh-my-fish/oh-my-fish#483] opened 2017-02-04 17:43 UTC
After upgrading to fish 2.5.0 via Homebrew I noticed several of OMF themes are now broken.

The pure theme now outputs this after every command,
```
test returned eval errors:
	invalid integer ''
```

[Most likely due to the following change,](https://fishshell.com/release_notes.html)
>Like other shells, the test builting now returns an error for numeric operations on invalid integers (#3346, #3581).

The batman theme appears to be completely busted, outputing the following,
```
~/.config/fish/functions/fish_prompt.fish (line 1): fst
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'off'
~/.config/fish/functions/fish_prompt.fish (line 1): off
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'snd'
~/.config/fish/functions/fish_prompt.fish (line 1): snd
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'off'
~/.config/fish/functions/fish_prompt.fish (line 1): off
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'fst'
~/.config/fish/functions/fish_prompt.fish (line 1): fst
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'off'
~/.config/fish/functions/fish_prompt.fish (line 1): off
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

sed: option requires an argument -- e
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
fish: Unknown command 'off'
~/.config/fish/functions/fish_prompt.fish (line 1): off
                                                    ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'dim'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): dim
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'fst'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): fst
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'dim'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): dim
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'fst'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): fst
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'dim'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): dim
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'off'
~/.local/share/omf/themes/batman/fish_right_prompt.fish (line 1): off
                                                                  ^
in command substitution
	called on line 16 of file ~/.local/share/omf/themes/batman/fish_right_prompt.fish

in function 'fish_right_prompt'
	called on standard input

in command substitution
	called on standard input

printf: not enough arguments
```

omf doctor output:

>Oh My Fish version:   4
OS type:              Darwin
Fish version:         fish, version 2.5.0
Git version:          git version 2.11.1
Git core.autocrlf:    no
Your shell is ready to swim.

**Comment by sagebind** [comment] 2017-02-04 22:49
The Batman theme appears to be broken on 2.4.0 as well. I'll look into this.

It looks like there's already an issue open for the Pure theme: https://github.com/rafaelrinaldi/pure/issues/38

**Comment by sagebind** [comment] 2017-02-04 23:22
@JamesMcMahon The Batman theme and a few other themes depend on `fish_greeting` to define functions (which is probably not a good design). If you are defining that function yourself, those functions will be broken. You may also have to re-open your terminal or run `omf reload` for those themes to work after install.

**Comment by JamesMcMahon** [comment] 2017-02-05 17:11
For the pure theme, `omf reload` didn't work, it's most likely the issue you called out above.

For the batman theme `omf reload` fixed it. I wasn't manually defining `fish_greeting` as far as I know, but perhaps the previous theme was setting something that conflicted. Either way I need to reload each time I set the batman theme.

Perhaps when switching a theme through `omf theme` it should automatically invoke `omf reload`?

**Comment by sagebind** [comment] 2017-02-05 19:30
`reload` isn't really all that pretty and I'd be hesitant to just add it everywhere to patch up issues that can be fixed in better ways.

I think the issue is with using `fish_greeting` to define functions. Since you are changing themes after fish is already started, it isn't going to execute batman's `fish_greeting`. That's why a reload fixes it, because then batman's `fish_greeting` gets executed. You can verify this yourself like this:

```
> omf theme batman
# theme is broken here
> fish_greeting
# now theme is fixed
```

The proper solution would be to fix these themes to not expect `fish_greeting` to always be called.

**Comment by onbjerg** [comment] 2017-02-06 07:51
krisleech and default is broken too. We should probably compile a list.

**Comment by sagebind** [comment] 2017-02-06 14:29
@onbjerg default isn't broken for me. If it is broken for  you, it is a different issue since default doesn't have a `fish_greeting` function.

**Comment by onbjerg** [comment] 2017-02-07 15:28
@sagebind It's broken for me on both the stable and dev channels for the latest fish version.

**Comment by sagebind** [comment] 2017-02-07 15:30
@onbjerg Can you share the output of the issue?

**Comment by JamesMcMahon** [comment] 2017-02-08 01:17
Default is working fine for me as well.

**Comment by sagebind** [comment] 2017-04-24 18:29
I found all themes using `fish_greeting` in a way that could cause issues by using a simple script. I either commented on or opened an issue for each of those themes:

* https://github.com/oh-my-fish/theme-batman/issues/1
* https://github.com/oh-my-fish/theme-dangerous/issues/6
* https://github.com/oh-my-fish/theme-fishbone/issues/5
* https://github.com/pastleo/theme-PastFish/issues/1
* https://github.com/umayr/theme-sushi/issues/4

Since there's no more we can do, and there's not an issue in OMF itself, I am closing this issue. Please use the links above to track fixing for individual themes.

**Closed by sagebind** 2017-04-24 18:29 UTC
Labels: a:themes, p:normal
