### ISSUE TITLE
Installer broken with a certificate error

### ISSUE THREAD

**Issue by pnunn** [oh-my-fish/oh-my-fish#799] opened 2021-01-04 03:06 UTC
Describe the problem you are having and how to reproduce it. Include any other additional context that can help us troubleshoot.

Linux installation.

```
curl -L https://get.oh-my.fish > install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

**Comment by lazyoracle** [comment] 2021-01-04 05:06
Reproduced the same. Seems like the certificate has expired.

**Comment by wezzle** [comment] 2021-01-05 09:58
Ran into the same issue. This seems to be on ipv6 only.

**Comment by pnunn** [comment] 2021-01-05 09:59
@wezzle I'm not on IP6

**Comment by lazyoracle** [comment] 2021-01-05 10:04
Not on ipv6, tried on ipv4 in a fresh Ubuntu 20.04 install

**Comment by wezzle** [comment] 2021-01-05 10:14
@pnunn My bad, it worked for me in Vivaldi on my ipv4 only machine but failed on an ipv6 enabled server. Just ran it through an online SSL validator and it seems there are chain certificates missing.

For those looking for a temporary workaround use:
`curl -L -k https://get.oh-my.fish > install`

I'd suggest you do validate the checksum to make sure it's the same as listed in the README.md:
`sha256sum install`

Before running the install script.

**Comment by yueyejinghun** [comment] 2021-01-08 11:27
Or one may directly curl the install file stored on GitHub repo, simply change the command to:
`
curl -L https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
`

**Comment by scorphus** [comment] 2021-01-22 22:36
Thanks for reporting, for your patience and for sharing workarounds.

Sincere apologies for the huge delay. This issue is solved.

Please confirm before we close this issue.

**Comment by yueyejinghun** [comment] 2021-01-23 01:07
I can confirm the issue has been solved.

**Comment by scorphus** [comment] 2021-01-23 11:22
Thanks for confirming, @yueyejinghun.

**Closed by scorphus** 2021-01-23 11:22 UTC

**Comment by dspacejs** [comment] 2021-11-04 11:39
I just encountered this problem after it being closed.

**Comment by scorphus** [comment] 2021-11-06 09:29
Can you please try again, @dspacejs? The link to the install script has changed. That fixes this issue for good.
