### ISSUE TITLE
Choosing to install package as theme instead of package

### ISSUE THREAD

**Issue by zhiayang** [oh-my-fish/oh-my-fish#466] opened 2016-12-31 03:04 UTC
Hello, opening another issue again, sorry about that oops

Anyway, how do I install something *as a theme*, so I can use `omf theme`? I have this custom theme over here: https://github.com/zhiayang/cmorrell-custom, that I can `omf install github.com/blabla`.

Unfortunately, that seems to classify it as a package, so `omf theme` cannot find the theme.

I'm setting up a new system, and nothing is going smoothly at all, and not just with fish lmao

**Comment by lfiolhais** [comment] 2016-12-31 10:14
Themes are differentiated from packages with the prefix `theme`. In your case you are going to have to rename your repo `theme-cmorrell-custom`. See [here](https://github.com/oh-my-fish/oh-my-fish/blob/master/docs/en-US/Packages.md#make-it-public)

**Comment by sagebind** [comment] 2017-01-06 04:12
@zhiayang This is a requirement we'd like to remove somehow in the future. See #191.

**Comment by sagebind** [comment] 2017-01-06 04:31
Closing as a duplicate of #191.

**Closed by sagebind** 2017-01-06 04:31 UTC
