### ISSUE TITLE
Installing oh-my-fish on cygwin 

### ISSUE THREAD

**Issue by NicolaSansom** [oh-my-fish/oh-my-fish#545] opened 2017-08-21 15:48 UTC
I installed Cygwin on windows 7 including curl and fish. I have read through issue #367 which seems to be the same as this issue, however, uninstalling and reinstalling Cygwin did not fix it.

The error I am getting:
```
$ curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0      1      0  0:03:14  0:02:30  0:00:44    40
100 16622  100 16622    0     0    110      0  0:02:31  0:02:30  0:00:01  270k
Installing Oh My Fish to /home/nicola.sansom/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
fatal: destination path '/home/nicola.sansom/.local/share/omf' already exists and is not an empty directory.
Install aborted: Error cloning repository!

```
The file does not exist when looking in explorer. `share` only has a fish folder within it.

Versions :
```
> set | grep OMF
⏎

> echo "$OMF_PATH"
⏎

> fish --version
fish, version 2.6.0

> git --version
git version 2.10.1.windows
```

Any idea what I can do to get this working?

**Comment by sagebind** [comment] 2017-08-21 16:37
Same issue as in #496 and #367. We never fully figured out the problem, but the issue is that Cygwin is lying to the installer that a directory exists when it does not, which is quite boggling. There could be something else going on though and it might be worth investigating again.

**Comment by NicolaSansom** [comment] 2017-08-21 19:25
@sagebind What should I try out next?

**Comment by oranja** [comment] 2017-08-22 08:11
Out on a limp here, but can you try to install the special Cygwin version of `git`? You should be able to find it in Cygwin's package manager. Then make sure that your Cywgin shell finds that version of `git` first (I guess that it won't say `.windows` in the version string?).



If that doesn't help, seeing that both `git` and `fish` suffer from the same problem, I tend to rule out `omf`, and even `fish` as the source of the problem. There might be a problem which stems from `fish` not being meant to run on Cygwin, but it seems to work to some (most?) people so it sounds unlikely.
Just for sports, I would check permissions again, for the entire path (`/home`, wherever it is on your PC, then `/home/nicola.sansom` and so forth), both from Cywgin and Windows Explorer.
And again, it sounds very strange because looking at the sources it seems more likely to report an existing directory as non-existent then, as in this case, the other way around.

**Comment by miwilc** [comment] 2017-08-30 04:30
I'm not sure about this can you try using swan?

http://www.starlig.ht

**Comment by daniel-oster** [comment] 2017-09-14 14:16
Hey
I just ran in to the same issue and think I figured it out. The problem is the virtual(?) file system messing the cygwin does. The files that can/can't be found have been added to a path so you need to use the windows path as cygwin sees them (/cygdrive/c/home/{user}/.local/..) 
You might be able to provide that path to the install to get it to work, what I did was to delete the folders in the windows explorer, install git through cygwin as well (apt-cyg install git, you need to install [apt-cyg](https://github.com/transcode-open/apt-cyg)  for that to work) and then tried again. Im a noob at both cygwin and fish, but my guess that the windows programs (git in my first attempt) sees the file system as windows so the paths get screwed up somehow... 
Not sure about the explination, but it solved my problems :-)
Good luck
Daniel

**Comment by oranja** [comment] 2017-09-14 15:09
Thanks @daniel-oster!
Your report confirms that we're finally on to something.
Git for Windows seems to get confused by Cygwin's unique environment.

I'll repeat the proposed workaround here for clarity:
If you're having the issue described here, while trying to install OMF through Cygwin, install the dedicated `git`-for-Cygwin package (`apt-cyg install git`, as @daniel-oster explains), and try again.

Let us know how it went.

**Comment by jakealstad** [comment] 2018-04-11 23:41
can confirm this works with the apt-cyg install git version of Git

**Comment by NoobTW** [comment] 2018-08-07 01:36
Can confirm this working after apt-cyg install git, too!

**Comment by sagebind** [comment] 2018-12-31 17:20
Closing as the problem appears to be solved! 🎉

**Closed by sagebind** 2018-12-31 17:20 UTC
