### ISSUE TITLE
Install aborted: Fish version 2.2.0 or greater required; you have

### ISSUE THREAD

**Issue by Clutchisback1** [oh-my-fish/oh-my-fish#885] opened 2022-02-02 05:00 UTC
When attempting to install fish on the latest version of kali I am getting the following error:

`Install aborted: Fish version 2.2.0 or greater required; you have` 

The error doesn't even populate the current version of fish I have installed but it can be seen when installing it.

```
┌──(clutchisback1㉿KaliDragon2022)-[/etc/github/oh-my-fish]
└─$ uname -a                                                                                                                                            127 ⨯
Linux KaliDragon2022 5.15.0-kali2-amd64 #1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux

──(clutchisback1㉿KaliDragon2022)-[/etc/github/oh-my-fish]
└─$ sudo apt-get install fish
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  doc-base
The following NEW packages will be installed:
  fish
0 upgraded, 1 newly installed, 0 to remove and 166 not upgraded.
Need to get 0 B/1,013 kB of archives.
After this operation, 6,128 kB of additional disk space will be used.
Selecting previously unselected package fish.
(Reading database ... 303666 files and directories currently installed.)
Preparing to unpack .../fish_3.3.1+ds-2_amd64.deb ...
Unpacking fish (3.3.1+ds-2) ...
Setting up fish (3.3.1+ds-2) ...
Processing triggers for kali-menu (2021.4.2) ...

┌──(clutchisback1㉿KaliDragon2022)-[/etc/github/oh-my-fish]
└─$ ./bin/install          
Checking for a sane environment...
Install aborted: Fish version 2.2.0 or greater required; you have 
```

### Installing WIth Verbose Mode

```
─$ ./bin/install --verbose                                                                                                                               1 ⨯
DEBUG: verbose turned on
Checking for a sane environment...
DEBUG: Command 'awk' is /usr/bin/gawk
DEBUG: Command 'basename' is /usr/bin/basename
DEBUG: Command 'cp' is /usr/bin/cp
DEBUG: Command 'cut' is /usr/bin/cut
DEBUG: Command 'date' is /usr/bin/date
DEBUG: Command 'dirname' is /usr/bin/dirname
DEBUG: Command 'env' is /usr/bin/env
DEBUG: Command 'fish' is /usr/bin/fish
DEBUG: Command 'fold' is /usr/bin/fold
DEBUG: Command 'head' is /usr/bin/head
DEBUG: Command 'mkdir' is /usr/bin/mkdir
DEBUG: Command 'mv' is /usr/bin/mv
DEBUG: Command 'readlink' is /usr/bin/readlink
DEBUG: Command 'rm' is /usr/bin/rm
DEBUG: Command 'sed' is /usr/bin/sed
DEBUG: Command 'sort' is /usr/bin/sort
DEBUG: Command 'tar' is /usr/bin/tar
DEBUG: Command 'tr' is /usr/bin/tr
DEBUG: Command 'which' is /usr/bin/which
DEBUG: Checking for a sane 'head' implementation
DEBUG: Checking for a sane 'sort' implementation
DEBUG: Checking for a working AWK interpreter
Install aborted: Fish version 2.2.0 or greater required; you have 
```                                                                     

Not really sure what to do. I've tried installing an older version of fish from their repo but had no success as of yet. Any help would be greatly appreciated. I've also looked at some of the other similar posts like this but didn't find a solution that seemed to work.

**Comment by scorphus** [comment] 2022-02-05 10:26
Thanks for the intro, @faho.

**Comment by scorphus** [comment] 2022-02-05 13:53
I wonder... is that the same package as in Ubuntu? Ubuntu's package works as per https://github.com/scorphus/oh-my-fish/runs/5078068933?check_suite_focus=true

**Comment by scorphus** [comment] 2022-02-05 14:06
Doesn't seem to be:

```
┌──(root💀e12c86694265)-[/]                                       
└─# fish --version                                                
fish, version                                                     
                                                                  
┌──(root💀e12c86694265)-[/]                                       
└─# fish --help                                                   
fish: Unknown command: less                                       
/usr/share/fish/functions/__fish_print_help.fish (line 129):      
            $pager                                                
            ^                                                     
in function '__fish_print_help' with arguments 'fish'             
                                                                  
┌──(root💀e12c86694265)-[/]                                       
└─# fish -li                                                      
Welcome to fish, the friendly interactive shell                   
Type help for instructions on how to use fish                     
root@e12c86694265 /# echo $version                                
                                                                  
root@e12c86694265 /# fish --version                               
fish, version                                                     
root@e12c86694265 /#                                              
root@e12c86694265 /# /app/install                                 
Checking for a sane environment...                                
Install aborted: Fish version 2.2.0 or greater required; you have 
root@e12c86694265 /# export version=3.3.1                         
set: Tried to change the read-only variable 'version'             
root@e12c86694265 / [1]# version=3.3.1 /app/install               
Checking for a sane environment...                                
Install aborted: Fish version 2.2.0 or greater required; you have 
root@e12c86694265 /#                                              
```

Sorry, @Clutchisback1. The installer would need to be improved to support a `--no-version-check`, which should be done whenever there's spare time from one of the contributors.

For now, I'd recommend installing OMF by hand – or changing the installer yourself and proposing a PR? – Unfortunately, there's no instructions for that, you'd have to read through [`install`](https://github.com/oh-my-fish/oh-my-fish/blob/master/bin/install) and replicate what's done there.

**Comment by faho** [comment] 2022-02-05 17:05
>I wonder... is that the same package as in Ubuntu? Ubuntu's package works as per https://github.com/scorphus/oh-my-fish/runs/5078068933?check_suite_focus=true

From that log:

>Run FISH_RELEASE=stock tools/ci-install-fish.sh
fish:
  Installed: (none)
  Candidate: 3.1.0-1.2
  Version table:
     3.1.0-1.2 500

That installs fish 3.1.0 for Ubuntu 20.04 "Focal Fossa" - the "latest" is a bit of a misnomer. The issue occurs with the Debian fish 3.3.1 package, which is only in Ubuntu 22.04 "Jammy Jellyfish".

Essentially, what needs to happen here is that Debian needs to fix their package.

**Comment by Clutchisback1** [comment] 2022-02-05 22:29
> 
> Sorry, @Clutchisback1. The installer would need to be improved to support a `--no-version-check`, which should be done whenever there's spare time from one of the contributors.
> 
> For now, I'd recommend installing OMF by hand – or changing the installer yourself and proposing a PR? – Unfortunately, there's no instructions for that, you'd have to read through [`install`](https://github.com/oh-my-fish/oh-my-fish/blob/master/bin/install) and replicate what's done there.

I appreciate the conversation on my issue @faho @scorphus ...I tried looking through the install script and fixing where the install got hung up but wasn't able to...hopefully we can get a fix for it to so other Kali Linux users can keep using fish. I also tried using an older version of fish but wasn't able to get it installed either. I did manage to make some sort of progress though  (if you can call it that) by uninstalling `fish-common` when attempting to install an older version of fish. Below is my new error that I was dealing with:

```
┌──(clutchisback1㉿KaliDragon2022)-[~]
└─$ fish --version
fish, version 3.3.1

┌──(clutchisback1㉿KaliDragon2022)-[/etc/github/oh-my-fish/bin]
└─$ ./install 
Checking for a sane environment...
Installing Oh My Fish to /home/clutchisback1/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
Writing bootstrap to /home/clutchisback1/.config/fish/conf.d/omf.fish...
Setting up Oh My Fish configuration...
fish: Unknown command: omf
omf install
^
Install aborted: Error installing plugins

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

Try rerunning with --verbose to see additional output.
```

Again, this is on the latest version of Kali that can be downloaded here: https://www.kali.org/get-kali/#kali-bare-metal if anyone has time or curiosity to try to replicate all this. The effort in fixing this goes a long way.

**Comment by MaxG-Enpal** [comment] 2022-02-06 10:28
> I wonder... is that the same package as in Ubuntu? Ubuntu's package works as per https://github.com/scorphus/oh-my-fish/runs/5078068933?check_suite_focus=true

Not for me. I get the same error on Ubuntu

**Comment by faho** [comment] 2022-02-06 12:34
>hopefully we can get a fix for it to so other Kali Linux users can keep using fish.

@Clutchisback1 Like I said in my initial comment, the solution is to not use Kali's fish package. 

You can use the upstream fish package from https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish instead. You need the "Debian" package.

There is no real fix possible for OMF, because the issue is that Debian's fish package doesn't have version information. Which means it can't tell the version.

**Comment by scorphus** [comment] 2022-02-06 13:12
There's already a bug reported for this issue at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001583, so I'm closing it.

Thanks again for much valid inputs, @faho.

**Closed by scorphus** 2022-02-06 13:12 UTC
Labels: installer, status: upstream issue
