### ISSUE TITLE
I see a `[I]` in my fish!

### ISSUE THREAD

**Issue by onionj** [oh-my-fish/oh-my-fish#937] opened 2023-09-11 22:38 UTC
I installed this project, after that I see a `[I]` in my fish!
Where is this section config file?

<img width="603" alt="Screenshot 2023-09-12 at 1 59 57 AM" src="https://github.com/oh-my-fish/oh-my-fish/assets/77416478/78725808-2454-4cb9-aa55-f11368ae8078">

<img width="603" alt="Screenshot 2023-09-12 at 2 00 55 AM" src="https://github.com/oh-my-fish/oh-my-fish/assets/77416478/32120e86-568f-4d4a-bb45-f12c1bbd937f">

How can I remove that green `[I]` ?

**Environment report**

```
Oh My Fish version:   7
OS type:              Darwin
Fish version:         fish, version 3.6.1
Git version:          git version 2.39.2 (Apple Git-143)
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
```

**Comment by scorphus** [comment] 2023-09-12 20:15
That's a feature of Fish and it is displayed by default when you activate vi mode.

Closing as a duplicate of https://github.com/oh-my-fish/oh-my-fish/issues/893#issuecomment-1094237556.

**Closed by scorphus** 2023-09-12 20:15 UTC

**Comment by onionj** [comment] 2023-09-12 21:15
Thanks
`fish_default_key_bindings` worked
