### ISSUE TITLE
themes not applying

### ISSUE THREAD

**Issue by superstefan420** [oh-my-fish/oh-my-fish#856] opened 2021-09-10 02:37 UTC
i have installed multiped themes and tried to apply them but only the left side after the prompt shows with themes like bobthefish. I tried removing my existing fish prompt with functions --erase fish_prompt but nothing will work

**Comment by Vistaus** [comment] 2021-09-12 12:00
I currently have the same issue. Worked fine for months, but not anymore.

**Comment by scorphus** [comment] 2021-09-12 12:42
I'm sorry you're having this issue. Could you please inform what themes are you having that issue with?

This seems like a duplicate of #671. Please check there for possible workarounds.

**Comment by Vistaus** [comment] 2021-09-12 12:49
With every theme.

**Comment by scorphus** [comment] 2021-09-12 14:58
1. What does `type fish_prompt` give as output?
2. What does `ls -lh (type -p fish_prompt)` give as output?

**Closed** 2022-02-01 22:33 UTC
