### ISSUE TITLE
Lambda theme slow/input lag in git repo

### ISSUE THREAD

**Issue by pydo** [oh-my-fish/oh-my-fish#605] opened 2018-04-08 15:57 UTC
**Fish version**
`fish, version 2.7.1`

**omf doctor**
```
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 2.7.1
Git version:          git version 2.7.4
Git core.autocrlf:    no
Your shell is ready to swim.
```

**OS/Distro**
`Linux user-super 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Terminal**
`GNOME Terminal 3.18.3`
`xterm-256color`

**Problem**
There is noticeable input lag when using the `lambda` theme inside a git repo
Here's a recording where I hold the `enter` key for 2 seconds then let go of the key. 
What happens is new lines keep appearing in the terminal for another 2 seconds after the key was
released.

https://asciinema.org/a/aumyJo90Ky8IRbLnitcLvzkZc

**Notes**
Here is the git repo I was using in the recording https://github.com/xmrMiner/xmrMiner
May be related to https://github.com/oh-my-fish/oh-my-fish/issues/598

**Comment by oranja** [comment] 2018-06-09 10:03
Hi @pydo,
Please direct package-specific issues to the package's repository first. In this case: https://github.com/hasanozgan/theme-lambda/issues

Not all packages are maintained by the OMF core team and not all package maintainers follow every OMF issue. By posting the issue in the package's repository there is a far greater chance that someone with the knowledge and power to solve it quickly will get your report.
If after a while you get no response and the repository seems not to be maintained anymore, reach back to us here and we might consider a different repository that provides the same functionality or - very rarely - forking and fixing the issue ourselves.

**Comment by sagebind** [comment] 2018-12-31 16:51
Note that this could also be caused by poor Git performance overall. See https://github.com/oh-my-fish/oh-my-fish/issues/598 again for that issue chain.

Closing this as it is likely either a problem with how Git is set up, or an issue with the Lambda theme itself. Feel free to open another issue if you find more problems. Thanks! 👋

**Closed by sagebind** 2018-12-31 16:51 UTC
