### ISSUE TITLE
The state of Oh my Fish and other frameworks

### ISSUE THREAD

**Issue by beckclib** [oh-my-fish/oh-my-fish#255] opened 2016-02-04 01:20 UTC
I have been using Oh my Fish! more or less satisfied :wink: and only recently found about Fisherman, Tackle, etc. I don't know whether I should switch or not.

They claim that Fisherman is faster and support for plugins and themes is there maybe, but I still haven't tried it yet. Are there any advantages of using Oh my Fish instead and what any opinions do you have?

Also tried asking there, but no response yet: https://github.com/fisherman/fisherman/issues/69

**Comment by oranja** [comment] 2016-02-04 08:28
Hello @becklib :)
The nature of open-source results often in the existence of several forks and alternatives. Each "product" has different goals, a different personality and so on. It's up to you, to choose what you like best, based on your own criteria. Personally, I want to encourage you to go take Fisherman for a spin. Try it out and see what works best for you.
I'm not "officially affiliated" with Oh-My-Fish, but I think I can speak for everyone here when I say that OMF's "advantage" is that we're not in a competition with anyone. We do it for the fun, we do it because we enjoy working together as a community, we learn something, we teach something, and along the way Oh-My-Fish takes shape. It's a work in progress. It has its ups and downs, rights and wrongs.
We are all a bit busy with our lives and it slows us down a little, but we have cool plans for the future. These changes are open for discussion, of course, and we try to keep a positive spirit.
So yes, other frameworks are leaner, faster, more beautiful, etc... But I believe that building a good ecosystem is a higher priority, and that overcoming infrastructure problems will follow naturally.

**Comment by beckclib** [comment] 2016-02-04 13:51
@oranja Thanks :) Maybe I'll give it a shot.

**Comment by oranja** [comment] 2016-02-04 15:22
I personally chose OMF because I think it gives the most complete and healthy solution to date and suits my needs best. It was true when I started using Fish and now I'm here trying to make sure it stays this way, for me and for others.
Now let's break it down.

[fundle] and [Tacklebox] are minimalist by design. It's great for some people, but I want a framework because I don't want to edit configuration files manually. In this regard, **Tacklebox** obviously falls short, while **fundle** does have a CLI, just not enough dedicated support for themes, which I find a very pleasing addition to the shell environment. So there's not much we can get by comparing **OMF** to **fundle** and **Tacklebox**, right? Let's assume they are both wonderful and move on.

Now we're finally comparing OMF to [Fisherman]. I haven't tried it out yet myself, so I will give you my concerns, and do correct me if you find that I'm wrong about any of my assumptions or conclusions:
1. My biggest concern with Fisherman is its flat hierarchy approach (fundle has this problem too). The result is a pretty fast shell, but it also means that nothing's stopping packages from clashing and overwriting each other. Sure, OMF might run into a very similar problem, but we retain the ability to make the framework find these clashes when they happen. Let's say two plugins use the same function and include it in their repositories. When you install the two plugins, nothing happens. When you uninstall one of them, suddenly the other breaks. I'd rather have a shell that's a bit slower to start (and I think we can solve this slow start problem). Furthermore, a flat file hierarchy makes it a lot more difficult to bypass the framework. What if you have a bug in Fisherman that's caused by a misbehaving plugin? How do you know which files belong to which package? Sure you can find out, but it's more frustrating now, isn't it? So thanks, but no thanks. As a programmer I learned many valuable lessons. Two of them is that optimization comes last and that well placed constraints are good for you.
2. I saw the codebase. It may be give a very fast shell, but I didn't feel comfortable there. In OMF, for comparison, it took me very little time from the moment I decided that I want to change something to the moment I submitted a PR. The code was fairly clear and self-explanatory, I saw how PRs and feedback are accepted, and I knew I can go ahead and submit my change. I had to redo my simple change many times before it got accepted, but feedback was always in a good, constructive spirit, so I decided my contribution to OMF should not stop there. In Fisherman I simply don't think it would have happened. Compare how many collaborators Fisherman has and how many we have here in OMF. Yes, Fisherman is young, but I'm telling you now that codebases usually only get messier. If you don't get people to lend a hand early on, I doubt it will happen later (people are more likely to rewrite everything from scratch).
3. Oh-My-Fish is an ecosystem. We write plugins and themes ourselves, and we try to provide other theme and plugin makers with everything they need. I'll give you two examples: (a) We are working to provide all themes and plugins with a good infrastructure, both for creating display elements and querying VCSs (git/hg/svn). There's no point in each theme reinventing the wheel. (b) We are working with upstream Fish people to get support for things that plugins (not just in OMF) can't support properly yet. Key-binding is a good example. If your framework supports key-bindings, trust me that there's some ugly and fragile hack involved.

I just want to add for the record, that everything I say about other frameworks I say because you asked for opinions. I have no intention to disrespect anyone's work, but I feel free to share my concerns. Again I repeat my encouragement to everyone who sees this to go out there, check the alternatives and choose for themselves. You can have a thousand reasons to choose one framework over the other, or you can just pick one because you like the name. Do what's right for you.

[fundle]: https://github.com/tuvistavie/fundle
[Tacklebox]: https://github.com/justinmayer/tacklebox
[Fisherman]: https://github.com/fisherman/fisherman

**Comment by derekstavis** [comment] 2016-02-05 02:33
I would like to add that managing a running project, with a base of users, committed to not break their installs, have been the main focus of Oh My Fish collaborators. It's actually very easy to create and destroy projects, abandoning your user base and forcing them to move to you newer awesome project, but that's now how we think.

*Having this said, I also would like to add that some of the Fisherman's marketing isn't actually very true*

##### Speed
Fisherman claims it's faster. The base of all fish shell frameworks is a system which add plugin's functions to `fish_function_path`, using fish's excellent [function autoloading mechanism](https://fishshell.com/docs/current/tutorial.html#tut_autoload), and provides "callbacks" for plugins for them to initialise their environments. 

The speed of shell load is directly proportional not only to the number of installed plugins, but also the time that plugins use on it's initialisation process. In my current setup this is the time that each plugin takes to load:

```
> fish -c exit
fonts 0.096
homebrew-github-token 0.089
artisan 0.090
battery 0.144
fasd 0.094
localhost 0.084
minimal-git-aliases 0.084
nvm 0.478
omf 0.103
thefuck 0.305
vcs 0.116
weather 0.086
```

You can see that most of the time was spent initialising `thefuck`, `vcs` and `nvm` plugins. So not to blame neither Oh My Fish, neither plugins, you must note that sometimes there's not much you can do to fix the timing issue in plugins:

* `thefuck` calls `thefuck --alias`, which is the official way of loading `thefuck` inside fish shell.
* `nvm` sources `nvm.sh` inside `bash` and do some heavy text processing.
* `vcs` probes for version control systems and setup some variables

##### Flat tree

This is, in **my opinion** a big bullshit. Oh My Fish replaced flat tree structure in plugins by a `functions` directory, to split actual functions from configuration/callbacks. Because Oh My Fish uses autoloading, if you do `autoload` plugin's root directory you would have clashes with repeated `init.fish` files (tip: path precedence wins). Using `functions` directory is very fishy, following a known directory name, as seen in `~/.config/fish/functions`, `/usr/local/Cellar/fish/2.2.0/share/fish/functions`, etc. Unfortunately, we have too keep supporting root directory autoloading, which is bad from a "the right way" view, but necessary for backwards compatibility.

**Comment by beckclib** [comment] 2016-02-05 03:25
Actually a reason why I asked in the first place this question is due Fisherman's claims to be 'faster' and I was having problems with Oh my Fish! startup time even though I don't use a lot of plugins. Always there is a noticeable delay when creating a new tab when I use bothecow theme. 

Another question, is Oh my Fish! planning support for Fisherman plugins?

**Comment by jrobeson** [comment] 2016-02-05 07:18
@beckclib: it's probably more of a problem with the theme

**Comment by bobthecow** [comment] 2016-02-05 07:21
it's entirely possible that it's an issue with the theme. do you notice the delay with `default` theme?

**Comment by bobthecow** [comment] 2016-02-05 07:22
(if it's an issue with the theme, please open an issue at [theme-bobthefish](https://github.com/oh-my-fish/theme-bobthefish) so we can help resolve it :smile:)

**Comment by beckclib** [comment] 2016-02-05 11:17
@jrobeson Disabling the theme improves things a bit, but I am still notice there is a slight lag.
@bobthecow I will again if I notice something.

I finally had a chance to try out Fisherman and to be fair, it does load faster. I am going to try out for a few days and see how it go!

Thank you all for your kindness. You can close if you wish.

**Comment by tannhuber** [comment] 2016-03-09 17:31
I use oh-my-fish for a simple reason. When the fisherman maintainer entered the oh-my-fish organization, he revoked my administrative rights of my sub projects. So I wasn't allowed to contribute to my own work anymore.

**Comment by bobthecow** [comment] 2016-03-09 22:46
:-/

**Closed** 2016-03-17 08:27 UTC

**Comment by simotek** [comment] 2016-05-19 13:33
I just stumbled upon this thread, for what its worth I use tacklebox + tackle still and keep it working for what i'm after, but I use it completely differently, I just use it as a tidy way to keep all my config in one repo (I only load my own personal tackle repo). I am the kind of person that prefers to modify there own config scripts and plugins though I also like being able to clone a git repo when I setup a new machine (I do it often) and point config.fish at it and be done.

**Comment by scorphus** [comment] 2016-05-19 14:07
Please, let me get off-topic here.
___
@derekstavis [once wrote](https://github.com/oh-my-fish/oh-my-fish/issues/255#issuecomment-180163677):
> […] In my current setup this is the time that each plugin takes to load:
> 
> ```
> fish -c exit
fonts 0.096
homebrew-github-token 0.089
artisan 0.090
battery 0.144
fasd 0.094
localhost 0.084
minimal-git-aliases 0.084
nvm 0.478
omf 0.103
thefuck 0.305
vcs 0.116
weather 0.086
```
> […]

@derekstavis: How about you sharing your profiling setup/script/function?
