### ISSUE TITLE
With update does not work lolcat in fish_greeting.fish

### ISSUE THREAD

**Issue by GittyMejorado** [oh-my-fish/oh-my-fish#914] opened 2022-09-27 04:47 UTC
I have updated fish and then omf, when updating omf it throws me the error:
Could not update colored_man_pages.fish.
Also lolcat no longer colors the greeting configured in the file fish_greeting.fish
And also when I open a terminal directly from the Dolphin file browser, it no longer puts the terminal in the directory where I am, the terminal opens directly in home.
Before when I opened a terminal directly from Dolphin I was placed in the directory where I was in Dolphin, for example if I was in Dolphin in etc/conky, the terminal opened directly in the etc/conky directory.
How can I solve the above?

I leave the data that omf doctor throws:

Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.5.1
Git version:          git version 2.25.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

**Comment by scorphus** [comment] 2022-10-02 16:36
Duplicate of #872

**Closed by scorphus** 2022-10-02 16:36 UTC
