### ISSUE TITLE
Missing symbols for themes

### ISSUE THREAD

**Issue by jiang-yuan** [oh-my-fish/oh-my-fish#900] opened 2022-05-22 16:09 UTC
for default theme, it cannot shows ⋊ symbol but only shows a retengular 
![image](https://user-images.githubusercontent.com/36291537/169704843-be12d069-d659-49df-9ceb-08fbc6bd3e43.png)
![image](https://user-images.githubusercontent.com/36291537/169704871-75462861-2973-4fa4-8616-33f8e798c14e.png)

I also try another theme 'slavic-cat' and also see a missing symbol ⫸ and ﾉ :
https://user-images.githubusercontent.com/36291537/169703842-d66fe2f4-8ab5-43c3-b06a-ffb66c3ec512.png

I installed omf by git clone and offline mode.

**Environment report**

Run the command `omf doctor` and paste the output here. Example:

```

Oh My Fish version:   7-44-gd428b72
OS type:              Linux ubuntu 18.04
Fish version:         fish, version 3.4.1
Git version:          git version 2.17.1
Git core.autocrlf:    no
```
PS. I am using win11 to connect ssh server. I try MobaXterm and powershell, they all cannot show the symbol correctly, but can work right when I connect ssh by Visual studio code.

**Comment by scorphus** [comment] 2022-05-29 20:41
Dupe of #871

**Closed by scorphus** 2022-05-29 20:41 UTC

**Comment by jiang-yuan** [comment] 2024-05-17 09:29
As #871 said, I try to install FiraCode-Regular.ttf and set it as the charset of my SSH terminal. It still does not work.
