### ISSUE TITLE
fish: Could not autoload item '_', it is already being autoloaded.

### ISSUE THREAD

**Issue by everhopingandwaiting** [oh-my-fish/oh-my-fish#607] opened 2018-04-15 11:51 UTC
```fish

fish install --path=~/.local/share/omf --config=~/.config/omf
Checking for a sane environment...
fish: Could not autoload item '_', it is already being autoloaded. This is a circular
dependency in the autoloading scripts, please remove it.
fish: Unknown command '_ %s is %s\n'
Installing Oh My Fish to /root/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
fatal: Unable to find remote helper for 'https'
Install aborted: Error cloning repository!

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

Try rerunning with --verbose to see additional output.



```

**Comment by everhopingandwaiting** [comment] 2018-04-15 11:51
```
fish install --path=~/.local/share/omf --config=~/.config/omf --verbose
DEBUG: verbose turned on
Checking for a sane environment...
fish: Could not autoload item '_', it is already being autoloaded. This is a circular
dependency in the autoloading scripts, please remove it.
fish: Unknown command '_ %s is %s\n'
DEBUG: Command 'awk' is /usr/bin/gawk
DEBUG: Command 'basename' is /usr/bin/basename
DEBUG: Command 'cp' is /usr/bin/cp
DEBUG: Command 'cut' is /usr/bin/cut
DEBUG: Command 'date' is /usr/bin/date
DEBUG: Command 'dirname' is /usr/bin/dirname
DEBUG: Command 'env' is /usr/bin/env
DEBUG: Command 'fish' is /usr/bin/fish
DEBUG: Command 'fold' is /usr/bin/fold
DEBUG: Command 'head' is /usr/bin/head
DEBUG: Command 'mkdir' is /usr/bin/mkdir
DEBUG: Command 'mv' is /usr/bin/mv
DEBUG: Command 'readlink' is /usr/bin/readlink
DEBUG: Command 'rm' is /usr/bin/rm
DEBUG: Command 'sed' is /usr/bin/sed
DEBUG: Command 'sort' is /usr/bin/sort
DEBUG: Command 'tar' is /usr/bin/tar
DEBUG: Command 'tr' is /usr/bin/tr
DEBUG: Command 'which' is /usr/bin/which
DEBUG: Checking for a sane 'head' implementation
DEBUG: Checking for a sane 'sort' implementation
DEBUG: Checking for a working AWK interpreter
DEBUG: Verifying Git implementation is not buggy Git for Windows
DEBUG: Verifying Git autocrlf is not enabled
Installing Oh My Fish to /root/.local/share/omf...
Using release channel "stable".
Cloning master from https://github.com/oh-my-fish/oh-my-fish.git...
fatal: Unable to find remote helper for 'https'
Install aborted: Error cloning repository!

Oh My Fish installation failed.

If you think that it's a bug, please open an
issue with the complete installation log here:

http://github.com/oh-my-fish/oh-my-fish/issues

```

**Comment by oranja** [comment] 2018-04-15 12:29
Hi @everhopingandwaiting,
We could use some more details... Fish version, OS kind, git version, etc...
Also is there any special reason you install under root?

**Comment by everhopingandwaiting** [comment] 2018-04-15 12:31
@oranja Yes , under root, should I  use normal account?

**Comment by everhopingandwaiting** [comment] 2018-04-15 12:32
```
root@izwz9id7ajv83ikpa2hhn2z ~# git --version
git version 2.17.0.252.gfe0a9ea
root@izwz9id7ajv83ikpa2hhn2z ~# fish -v
fish, version 2.3.1
root@izwz9id7ajv83ikpa2hhn2z ~# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

root@izwz9id7ajv83ikpa2hhn2z ~#

```

**Comment by oranja** [comment] 2018-06-09 09:27
Hi @everhopingandwaiting,
Any news on this?

**Comment by josemaX** [comment] 2018-06-14 19:18
If you are using git compiled from sources, install curl-devel and build git again.
That worked for me.
The key is: "fatal: Unable to find remote helper for 'https'"

**Comment by sagebind** [comment] 2018-12-31 16:32
Looks like Git is compiled without HTTPS support, which OMF requires.

Closing as the root cause seems to be identified. Thanks!

**Closed by sagebind** 2018-12-31 16:32 UTC
