### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by jinleileiking** [oh-my-fish/oh-my-fish#535] opened 2017-08-03 06:27 UTC
```
[root@tjwq01-ibu-video007106 ksyun]# curl -L https://get.oh-my.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16622  100 16622    0     0   1071      0  0:00:15  0:00:15 --:--:--  1456
fish: unexecutable block
fish: Could not locate end of block. The “end” command is missing, misspelled or a “;” is missing.
Standard input: #!/usr/bin/env fish
                ^

       end - end a block of commands.


   Synopsis
       begin; [COMMANDS...] end
       if CONDITION; COMMANDS_TRUE...; [else; COMMANDS_FALSE...;] end
       while CONDITION; COMMANDS...; end
       for VARNAME in [VALUES...]; COMMANDS...; end
       switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end


   Description
       end ends a block of commands. For more information, read the
       documentation for the block constructs, such as if, for and while.

       The end command does not change the current exit status.

[root@tjwq01-ibu-video007106 ksyun]# fish -v
fish, version 1.23.1
```

**Comment by oranja** [comment] 2017-08-03 06:32
Hi @jinleileiking,
The version of `fish` which you are using is not supported by OMF (requires `fish` >= 2.2).

(Duplicate of issue #533)

**Comment by sagebind** [comment] 2017-08-11 15:56
Closing as duplicate of #533.

**Closed by sagebind** 2017-08-11 15:56 UTC
