### ISSUE TITLE
Getting errors on when setting omf theme

### ISSUE THREAD

**Issue by comfortablynick** [oh-my-fish/oh-my-fish#648] opened 2018-10-15 18:09 UTC
Operating system: Ubuntu 18.04.1 LTS (WSL)
Fish version: 2.7.1-1538
OMF version: 6
Git version: 2.17.1

I have tried removing and reinstalling OMF and packages, but I still get this output when I execute `omf theme {theme_name}`:

```fish
dev ❯ omf theme bobthefish
set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85):
    and set -e fish_function_path[$function_indexes]
        ^
in function “__autoload_erase”
        called on line 6 of file ~/.local/share/omf/lib/autoload.fish
        with parameter list “/c/Users/me/.config/omf/themes/pure /c/Users/me/.local/share/omf/themes/pure /c/Users/me/.config/omf/themes/pure/functions /c/Users/me/.local/share/omf/themes/pure/functions”

in function “autoload”
        called on line 25 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
        with parameter list “-e /c/Users/me/.config/omf/themes/pure /c/Users/me/.local/share/omf/themes/pure /c/Users/me/.config/omf/themes/pure/functions /c/Users/me/.local/share/omf/themes/pure/functions”

in function “omf.theme.set”
        called on line 18 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
        with parameter list “bobthefish”

in function “omf.cli.theme”
        called on line 3 of file -
        with parameter list “bobthefish”

in function “__omf_last_command”
        called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function “omf”
        called on standard input
        with parameter list “theme bobthefish”


       set - display and change shell variables.

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type “help set” for related documentation

```

Everything seems to work OK, but it's annoying to get this message. I don't know if it's specific to my config or not. 

Ultimately I'm hoping to be able to set the theme in my `config.fish` depending on certain parameters, such as `SSH_CONNECTION`. If there's a better way to do it, I'm all ears! 

Thank you,
Nick

**Comment by mojoTX** [comment] 2018-11-27 23:30
What do you see if you type `omf doctor`?

**Comment by comfortablynick** [comment] 2018-11-30 18:39
Unfortunately, I'm not using omf anymore. I wrote a function to load my own theme based on environment variables at startup. I'll keep an eye on omf development and check it out again if improved theme handling is ever added.

**Comment by lukasab** [comment] 2019-06-04 18:05
I'm having the same problem when I try to install some themes

`set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85): 
    and set -e fish_function_path[$function_indexes]
        ^`
When I run `omf doctor` I receive:

`Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.21.0
Git core.autocrlf:    no
Your shell is ready to swim.` 

It seems that the theme was installed but for some reason, it is giving me this error.

**Comment by Strum355** [comment] 2019-06-27 12:19
Same issue here
`omf doctor`:
```
omf doctor                                                                                                                                                                                      Thu 27 Jun 2019 01:18:21 PM IST
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.22.0
Git core.autocrlf:    no
Your shell is ready to swim.
```

**Comment by kfkonrad** [comment] 2019-06-27 12:24
@lukasab @Strum355 does this happen on a fresh installation of OMF? What themes cause the bug and can you provide steps to reproduce the error?

**Comment by Strum355** [comment] 2019-06-27 13:49
This is a fairly fresh OMF installation, little installed besides <(10|5) plugins and one theme. I simply installed bobthefish and got the error and once again got the error when changing back to shellder, which i had already installed @kfkonrad

**Comment by timgivois** [comment] 2019-07-19 00:07
I'm having the same issue

**Comment by baonq243** [comment] 2019-08-16 14:08
Same issue

**Comment by naoey** [comment] 2019-08-18 11:33
Unsure if related, but recently I've started seeing errors with another theme after every command:
```
λ omf theme sushi                                                                                                                                                   (~) 16:59:48
printf: Expected at least 1 args, got only 0
```

`omf doctor` shows:
```
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.2
Git version:          git version 2.20.1 (Apple Git-117)
Git core.autocrlf:    no
Your shell is ready to swim.
printf: Expected at least 1 args, got only 0
```

**Comment by RafalSladek** [comment] 2019-08-21 04:58
same here 
`omf theme default` 
results with

```
set --erase: Expected 1 args, got 2
~/.local/share/omf/lib/autoload.fish (line 85):
    and set -e fish_function_path[$function_indexes]
        ^
in function '__autoload_erase'
	called on line 6 of file ~/.local/share/omf/lib/autoload.fish
	with parameter list '/Users/rsladek/.config/omf/themes/spacefish /Users/rsladek/.local/share/omf/themes/spacefish /Users/rsladek/.config/omf/themes/spacefish/functions /Users/rsladek/.local/share/omf/themes/spacefish/functions'

in function 'autoload'
	called on line 25 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
	with parameter list '-e /Users/rsladek/.config/omf/themes/spacefish /Users/rsladek/.local/share/omf/themes/spacefish /Users/rsladek/.config/omf/themes/spacefish/functions /Users/rsladek/.local/share/omf/themes/spacefish/functions'

in function 'omf.theme.set'
	called on line 18 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
	with parameter list 'default'

in function 'omf.cli.theme'
	called on line 3 of file -
	with parameter list 'default'

in function '__omf_last_command'
	called on line 51 of file ~/.local/share/omf/pkg/omf/functions/omf.fish

in function 'omf'
	called on standard input
	with parameter list 'theme default'


       set - display and change shell variables.

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type 'help set' for related documentation```

`omf doctor`

output
```
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.2
Git version:          git version 2.23.0
Git core.autocrlf:    input
Your shell is ready to swim.
```

**Comment by liangti** [comment] 2019-09-02 17:22
Same here
```
Oh My Fish version:   6
OS type:              Darwin
Fish version:         fish, version 3.0.2
Git version:          git version 2.20.1 (Apple Git-117)
Git core.autocrlf:    no
```
I am using Mac.

So when I run `fish` there's `[I]` in front of my prompt. And that `[I]` disappear when I switch theme from bobthefish to default, and the error message above show.

When I destroy omf the `[I]` still exist. I am suspecting that omf somehow have a not compatible shell embed to fish script. Should be easy to figure out if someone familiar with omf script

**Comment by lbrun25** [comment] 2019-10-11 20:42
Same issue

**Comment by LikoIlya** [comment] 2019-12-06 10:55
Same

**Comment by odirar** [comment] 2019-12-16 07:22
Same

**Comment by k0nk** [comment] 2019-12-28 11:34
Same

**Comment by Norec39** [comment] 2020-01-08 08:45
Same

**Comment by monoverse** [comment] 2020-01-30 13:29
Having the same issue.

I wonder if this has smth to do with the _chain_ theme installed. When I uninstall the theme, everything seems to be back to normal.

I also noticed that the chain theme stores its "fish_prompt.fish" in a different location:

`~/.local/share/omf/themes/chain/functions/fish_prompt.fish`

.. instead of ..

`/.local/share/omf/themes/chain/fish_prompt.fish`

.. which seems to be the standard location.

**Comment by bobthecow** [comment] 2020-01-31 14:08
Themes can put their `fish_prompt.fish` either in the top level or inside `functions`. It works the same either way.

I know chain has a "compile" feature. That might be messing with things. What does `functions fish_prompt` say when you're having the issue?

**Comment by asedel** [comment] 2020-02-18 19:15
@bobthecow just reproduced switching from bobthefish to default:

```
⋊> ~/.l/s/o/themes on myv6  omf theme bobthefish                                                                                                                                                     13:09:34
 default  ~/.l/s/omf   myv6  themes  omf theme default                                                                                                                          Tue Feb 18 13:09:38 2020
set --erase: Expected 1 args, got 2

~/.local/share/omf/lib/autoload.fish (line 48):
    and set -e fish_function_path[$function_indexes]
        ^
in function '__autoload_erase' with arguments '/Users/adam.edelstein/.config/omf/themes/bobthefish /Users/adam.edelstein/.local/share/omf/themes/bobthefish /Users/adam.edelstein/.config/omf/themes/bobthefish/functions /Users/adam.edelstein/.local/share/omf/themes/bobthefish/functions'
	called on line 5 of file ~/.local/share/omf/lib/autoload.fish
in function 'autoload' with arguments '-e /Users/adam.edelstein/.config/omf/themes/bobthefish /Users/adam.edelstein/.local/share/omf/themes/bobthefish /Users/adam.edelstein/.config/omf/themes/bobthefish/functions /Users/adam.edelstein/.local/share/omf/themes/bobthefish/functions'
	called on line 24 of file ~/.local/share/omf/pkg/omf/functions/themes/omf.theme.set.fish
in function 'omf.theme.set' with arguments 'default'
	called on line 17 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.theme.fish
in function 'omf.cli.theme' with arguments 'default'
	called on line 2 of file -
in function '__omf_last_command' with arguments 'default'
	called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'theme default'

(Type 'help set' for related documentation)
⋊> ~/.l/s/o/themes on myv6  functions fish_prompt                                                                                                                                                    13:09:40
# Defined in /Users/adam.edelstein/.config/fish/functions/fish_prompt.fish @ line 5
function fish_prompt
  set -l last_command_status $status
  set -l cwd

  if test "$theme_short_path" = 'yes'
    set cwd (basename (prompt_pwd))
  else
    set cwd (prompt_pwd)
  end

  set -l fish     "⋊>"
  set -l ahead    "↑"
  set -l behind   "↓"
  set -l diverged "⥄ "
  set -l dirty    "⨯"
  set -l none     "◦"

  set -l normal_color     (set_color normal)
  set -l success_color    (set_color $fish_pager_color_progress 2> /dev/null; or set_color cyan)
  set -l error_color      (set_color $fish_color_error 2> /dev/null; or set_color red --bold)
  set -l directory_color  (set_color $fish_color_quote 2> /dev/null; or set_color brown)
  set -l repository_color (set_color $fish_color_cwd 2> /dev/null; or set_color green)

  if test $last_command_status -eq 0
    echo -n -s $success_color $fish $normal_color
  else
    echo -n -s $error_color $fish $normal_color
  end

  if git_is_repo
    if test "$theme_short_path" = 'yes'
      set root_folder (command git rev-parse --show-toplevel 2> /dev/null)
      set parent_root_folder (dirname $root_folder)
      set cwd (echo $PWD | sed -e "s|$parent_root_folder/||")
    end

    echo -n -s " " $directory_color $cwd $normal_color
    echo -n -s " on " $repository_color (git_branch_name) $normal_color " "

    if git_is_touched
      echo -n -s $dirty
    else
      echo -n -s (git_ahead $ahead $behind $diverged $none)
    end
  else
    echo -n -s " " $directory_color $cwd $normal_color
  end

  echo -n -s " "
end
⋊> ~/.l/s/o/themes on myv6
```

omf doctor says :
```
⋊> ~/.l/s/o/themes on myv6  omf doctor                                                                                                                                                               13:09:46
Oh My Fish version:   6-2-gf959856
OS type:              Darwin
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.0 Git version:          hub version 2.14.1
Git core.autocrlf:    no
Your shell is ready to swim.
⋊> ~/.l/s/o/themes on myv6
```

the only changes on 'myv6' versus the v6 tag is my local fixes for the caret issue "> /dev/null ^>1 " replaced with " &> /dev/null " 

its interesting to note that I can go back and forth between themes that don't use function dirs or between several that don't and one that does, but when I go between two that use functions dirs ( like bobthefish and spacefish)  the changeover isn't complete until I blow away the file... I can go bobthefish to spadefish ok... it isn't until I run omf doctor after switching back that things get repaired for bobthefish again. subsequently I have to run omf doctor each time I switch back and forth between the two after the 'first' switch

I suspect something in the removal code is going wrong

**Comment by mmgaribaldi** [comment] 2020-02-18 22:05
I had a similar issue, and I got rid of it running:

```
exec fish
```

inside a fish session.

**Comment by dreki** [comment] 2020-02-23 02:50
@mmgaribaldi's tip fixed it for me. I was a little surprised it did. Prior to doing this I also trashed my `fish_variables` file (a theme updated it and screwed it up).

**Comment by queenkjuul** [comment] 2020-02-27 22:01
I have this issue, and this is on a brand-new installation of everything--i just installed fish yesterday,  and this is my first time ever using omf, and the problem happens with basically every omf function. @asedel 's solution works, changing it to `&>` instead of `^&1`, but this happens with every function--installing themes, switching themes, `new`, everything so far I have tried. So I would have to go through and edit every single file, it would seem. 

Is this a Mac issue? I am using fish on macOS 10.15.3, fish 3.1.0 via brew. `exec fish` did not help me

    ➤➤➤➤➤ omf doctor
    Oh My Fish version:   6
    OS type:              Darwin
    Fish version:         fish, version 3.1.0
    Git version:          git version 2.25.0
    Git core.autocrlf:    no
    Your shell is ready to swim.

```
➤➤➤➤➤ omf -v
Oh My Fish version 6
```


---

```➤➤➤➤➤ omf install bang-bang
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package bang-bang
~/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish (line 11): Expected a string, but instead found a '&'
    if not grep $record $bundle > /dev/null ^&1
                                             ^
from sourcing file ~/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish
	called on line 1 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish
in command substitution
	called on line 55 of file ~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish
in function 'omf.packages.install' with arguments 'bang-bang'
	called on line 13 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish
in function 'omf.cli.install' with arguments 'bang-bang'
	called on line 2 of file -
in function '__omf_last_command' with arguments 'bang-bang'
	called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'install bang-bang'
source: Error while reading file '/Users/julie.hill/.local/share/omf/pkg/omf/functions/bundle/omf.bundle.add.fish'
fish: Unknown command: omf.bundle.add
~/.local/share/omf/pkg/omf/functions/packages/omf.packages.install.fish (line 55):
    omf.bundle.add package $name_or_url
    ^
in function 'omf.packages.install' with arguments 'bang-bang'
	called on line 13 of file ~/.local/share/omf/pkg/omf/functions/cli/omf.cli.install.fish
in function 'omf.cli.install' with arguments 'bang-bang'
	called on line 2 of file -
in function '__omf_last_command' with arguments 'bang-bang'
	called on line 50 of file ~/.local/share/omf/pkg/omf/functions/omf.fish
in function 'omf' with arguments 'install bang-bang'
✔ bang-bang successfully installed.```

**Comment by queenkjuul** [comment] 2020-02-27 22:08
So of course immediately after commenting, I find this commit:

https://github.com/oh-my-fish/oh-my-fish/commit/a6a67be60b1f1a4d305775847b81a5cc7d0c2f9e

which indicates that they output redirection is changing. So I uninstalled omf and reinstalled using dev channel and so far it is working ok. Will report any new issues if I find them.

**Comment by asedel** [comment] 2020-02-28 04:01
Seems like we should still fix this on master ahead of the dev branch though so that people who install the stable default version aren't greeted with immediate failures.  Could be very off putting for a first install to fail.

**Comment by bobthecow** [comment] 2020-03-21 17:17
We should just release a new version with the fix :) 

Closing in favor of #745 (see the workaround of switching to dev channel in https://github.com/oh-my-fish/oh-my-fish/issues/745#issuecomment-601196111)

**Closed by bobthecow** 2020-03-21 17:17 UTC
