### ISSUE TITLE
Omf error when installing multiple themes

### ISSUE THREAD

**Issue by pydo** [oh-my-fish/oh-my-fish#620] opened 2018-06-19 18:40 UTC
**fish info**:
```» omf doctor
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 2.7.1
Git version:          git version 2.17.1
Git core.autocrlf:    no
```

**Description**
`omf` outputs an error when installing the following themes:
- `cbjohnson`
- `chain`
- `lambda`

**Repro**
1. `omf install cbjohnson`
2. `omf install chain`
3. `omf install lambda`

**Expected behavior**
3. The lambda package should install without returning any errors and should be set
as my current theme. I'm assuming this is an issue with `omf` not properly swapping prompts after I installed a new theme

**Actual behavior**

 ```
» omf install lambda
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package lambda
✔ lambda successfully installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
user at user-desktop in ~
```
doctor output:
```
user at user-desktop in ~
» omf doctor
Oh My Fish version:   6
OS type:              Linux
Fish version:         fish, version 2.7.1
Git version:          git version 2.17.1
Git core.autocrlf:    no
Warning: fish_prompt.fish is overridden.
  fish_config command persists the prompt to ~/.config/fish/functions/fish_prompt.fish
  That file takes precedence over Oh My Fish's themes. Remove the file to fix it:
  rm ~/.config/fish/functions/fish_prompt.fish

If everything you use Oh My Fish for is working fine, please don't worry and just ignore the warnings. Thanks!
```

Why doesn't `omf` have a command for setting/enabling themes? The only available theme commands seem to be install and list. But what if I want to enable a theme that I already installed?

I resolved the issue by deleting my old `~/.config/fish/functions/fish_prompt.fish`, so I'm actually opening this issue as a bug report.
I'd appreciate any input, thanks!

**Comment by oranja** [comment] 2018-06-20 08:18
The command for switching themes (from installed ones) is `omf theme <theme_name>`.
e.g. `omf theme chain`.

That being said, I suspect that there's still a bug with this, where the previous theme sticks even after selecting a different theme, and you have to run `omf reload`.

**Comment by pydo** [comment] 2018-06-23 12:12
@oranja Were you able to repro this issue following the steps I listed? If not, I can try to make a docker image that will consistently reproduce this bug.

**Comment by oranja** [comment] 2018-06-24 08:30
Yes @pydo I can reproduce this with the steps you listed. Thank you for the detailed report.
I will investigate further as soon as I get a chance.

**Comment by sorenmortensen** [comment] 2019-03-13 16:13
I have this problem every time I try to switch themes using `omf theme <theme_name>`, and am forced to delete my `fish_prompt.fish` file every time.

In addition, when I run `omf theme toaster`, for example, I receive the following message:

```
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
Theme not installed!
Install it using omf install toaster
```

But when I run `omf install toaster` as instructed, I receive the following, inconsistent, message:

```
Updating https://github.com/oh-my-fish/packages-main master... Done!
Error: toaster already installed.
Conflicting prompt setting.
Run omf doctor and fix issues before continuing.
```

**Comment by jhimon** [comment] 2020-12-06 16:36
remove lambda by 
`omf remove lambda`
worked for me

**Comment by jhimon** [comment] 2020-12-06 16:37
Maybe there is problem with **lambda** theme. Remove it by `omf remove lambda`.
Worked for me

**Comment by ColtonIdle** [comment] 2020-12-08 15:19
You might be running into https://github.com/oh-my-fish/oh-my-fish/issues/671

**Comment by conner-mcnicholas** [comment] 2020-12-28 20:20
I have found a root cause and solution, at least for certain themes:

When you apply a new theme, there is a symlink set from:

```~/.config/fish/functions/fish_prompt.fish```
to 
```~/.local/share/omf/themes/**EXAMPLE_THEME**/fish_prompt.fish```

If you inspect the content of a properly functioning theme, that latter file will exist, along with a few others.  But certain themes do not package that file correctly, either by misnaming it, or putting it in a subdirectory.  For "lolfish", it is named lol.fish.  For "plain" it is within a subfolder called functions.  

You can individually fix these themes by copying the file that is meant to set the theme to the intended name of fish_prompt.fish.  

Example for lolfish.

```
omf install lolfish    # no apparent theme change
cd ~/.local/share/omf/themes/lolfish/    # this dir contains different files for some themes
cp lol.fish fish_prompt.fish    # fish_prompt was missing, so this is the fix
omf theme default    # just to allow refresh 
omf theme lolfish    # notice theme changes properly
```

**Comment by scorphus** [comment] 2020-12-29 10:51
Please, let's keep the conversation in #671 only. Closing this as duplicate.

**Closed by scorphus** 2020-12-29 10:51 UTC
Labels: duplicate
